[package]
name = "helmet-core"
version = "0.2.0"
edition = "2021"
authors = ["Daniel Kovacs <kovacsemod@gmail.com>"]
description = "HTTP security headers middleware core for various web frameworks"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/danielkov/rust-helmet"
repository = "https://github.com/danielkov/rust-helmet"
keywords = ["helmet", "security", "middleware", "rust", "web"]
categories = [
  "web-programming",
  "network-programming",
  "web-programming::http-server",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
